# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff307463392b86fad5ad0b1f68c44c955854e6e447db4ce9adf85a8f8a6ea7b520ebb19593c6fd18e0ac5744c83b102eb6be1e5d00e7f326fe20ea0910cc01ec

test:
  secret_key_base: 43bf3474299de33ee79a16d532bd283c9a1aa6c2faa2378ed42c44f078fc8e7ac7e48743cfb4147f653702c58e4674a6623df3b5586f294154b897d072321363

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
